platform:ios, '8.0'  
pod 'AFNetworking', '~> 2.1.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'YYCategories', '~> 0.9.3'
pod 'YYJSONHelper', '~> 1.0.6'
pod 'LLBootstrapButton', '~> 0.0.1'
pod 'SWTableViewCell', '~> 0.3.7'
